name = "B0Map"
uuid = "26d27508-09c5-44d0-86be-f4e37b03a7e6"
version = "0.1.3"
authors = ["Carl Ganter <cganter@tum.de>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SavitzkyGolay = "c4bf5708-b6a6-4fbe-bcd0-6850ed671584"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
VP4Optim = "8687cf0f-8f6d-4dd6-8e27-64e326ab5325"

[compat]
ADTypes = "1.21.0"
ChunkSplitters = "3.1.0"
Compat = "4.17.0"
DocumenterTools = "0.1.21"
FFTW = "1.8.1"
LinearAlgebra = "1.11.0"
LinearSolve = "3.44.0"
Optim = "2.0.0"
Random = "1.11.0"
Revise = "3.7.2"
SavitzkyGolay = "0.9.1"
StaticArrays = "1.9.11"
Statistics = "1.11.1"
StatsBase = "0.34.4"
Test = "1.11.0"
TimerOutputs = "0.5.28"
VP4Optim = "1.0.8"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
